language: 'ruby'

env:
  global:
    - 'ARTIFACTS_AWS_REGION=us-east-1'
    - 'ARTIFACTS_S3_BUCKET=drogus-artifacts'
    - secure: "pY4vu9rgAsBxrytcoIqzogEFhwoHGU0QwNjyMUHWv0mwtayEbhd3gr8xd5a3\nuxcDXOIy/tS1epU+W8fmWz85FgRIaHGhUt+7YHtyAfFcgaCZp/IcywWfXXBm\nT1ear0yWY+8ZCygTRU6+8Di7BFB5436Mdmtv2uYT4x1x98NZcpQ="

before_script:
  - 'export `curl -s https://raw.github.com/gist/4126639/travis-encrypt.rb | ruby -- "" decrypt -d .encrypted-vars`'
  - 'bash < <(curl -s https://raw.github.com/gist/4089736/install-artifacts.sh)'

after_test:
  - "travis-artifacts upload --path screenshots --path logs"
after_failure:
  - "travis-artifacts upload --path debug"
after_success:
  - "travis-artifacts upload --path build"
