language: 'ruby'

env:
  global:
    - 'ARTIFACTS_AWS_REGION=us-east-1'
    - 'ARTIFACTS_S3_BUCKET=drogus-artifacts'
    - secure: "Ty2niXJaugen5EbfDaJlHEQk1KlTfFlDHaMJ/V8WZp+6p/2g+7hcn2vGXKIE\nqnQjHS+/fJQqG1RsAlunb0c6MLbDKEi/5MZ9GOROsVtby++RX4F/memChnHE\nHuycPWjIVoUPrygZysTjfd5qVMO/V69bNIBVqYGea7qhUst18lw="

before_script:
  - 'export `curl -s https://raw.github.com/gist/4126639/travis-encrypt.rb | ruby -- "" decrypt -d .encrypted-vars`'
  - "gem install travis-artifacts"

after_script:
  - "travis-artifacts upload --path screenshots --path logs"
after_failure:
  - "travis-artifacts upload --path debug"
after_success:
  - "travis-artifacts upload --path build"
